export type LangValue = 'en' | 'zh' | 'ja' | 'pt' | 'es' | 'ko' | 'fr' | 'de' |
  'ue' | 'ar' | 'th' | 'ru' | 'hi' | 'bn' | 'ur' | 'id' | 'sw' | 'mr' | 'te' | 'tr' | 'ta' | 'vi' | 'it' | 'gu' | 'jw' | 'fa' | 'pl' | 'uk' | 'ml' | 'kn' | 'or' | 'my' | 'nl' | 'su' | 'ha' | 'pa' | 'yo' | 'mi' | 'cs' | 'el' | 'hu' | 'sv' | 'be' | 'km' | 'tg' | 'so' | 'uz' | 'az' | 'ro' | 'kk' | 'si' | 'da' | 'sk' | 'fi' | 'no' | 'he' | 'tt' | 'hr' | 'bg' | 'sr' | 'ca' | 'sl' | 'lt' | 'lv' | 'et' | 'sq' | 'hy' | 'mn' | 'ne' | 'ps' | 'bo' | 'eu' | 'cy' | 'br' | 'lb' | 'is' | 'fo' | 'yi' | 'gl' | 'af' | 'am' | 'as' | 'ba' | 'bs' | 'ka' | 'kl' |
  'aw' | 'rw' | 'ku' | 'lo' | 'mg' | 'mt' | 'sd' | 'ti' | 'tk' | 'zu' | 'yue' | 'haw'

export const langs: { value: LangValue, name: string }[] = [
  { "value": "en", "name": "English" },
  { "value": "zh", "name": "汉语" },
  { "value": "ja", "name": "日本語" },
  { "value": "pt", "name": "Português" },
  { "value": "es", "name": "Español" },
  { "value": "ko", "name": "한국어" },
  { "value": "fr", "name": "Français" },
  { "value": "de", "name": "Deutsch" },
  { "value": "yue", "name": "粵語" },
  { "value": "ar", "name": "العربية" },
  { "value": "th", "name": "ไทย" },
  { "value": "ru", "name": "Русский" },
  { "value": "hi", "name": "हिन्दी" },
  { "value": "bn", "name": "বাংলা" },
  { "value": "ur", "name": "اردو" },
  { "value": "id", "name": "Bahasa Indonesia" },
  { "value": "sw", "name": "Kiswahili" },
  { "value": "mr", "name": "मराठी" },
  { "value": "te", "name": "తెలుగు" },
  { "value": "tr", "name": "Türkçe" },
  { "value": "ta", "name": "தமிழ்" },
  { "value": "vi", "name": "Tiếng Việt" },
  { "value": "it", "name": "Italiano" },
  { "value": "gu", "name": "ગુજરાતી" },
  { "value": "jw", "name": "Basa Jawa" },
  { "value": "fa", "name": "فارسی" },
  { "value": "pl", "name": "Polski" },
  { "value": "uk", "name": "Українська" },
  { "value": "ml", "name": "മലയാളം" },
  { "value": "kn", "name": "ಕನ್ನಡ" },
  { "value": "or", "name": "ଓଡ଼ିଆ" },
  { "value": "my", "name": "မြန်မာဘာသာ" },
  { "value": "nl", "name": "Nederlands" },
  { "value": "su", "name": "Basa Sunda" },
  { "value": "ha", "name": "Hausa" },
  { "value": "pa", "name": "ਪੰਜਾਬੀ" },
  { "value": "yo", "name": "Yorùbá" },
  { "value": "mi", "name": "Māori" },
  { "value": "cs", "name": "Čeština" },
  { "value": "el", "name": "Ελληνικά" },
  { "value": "hu", "name": "Magyar" },
  { "value": "sv", "name": "Svenska" },
  { "value": "be", "name": "Беларуская мова" },
  { "value": "km", "name": "ភាសាខ្មែរ" },
  { "value": "tg", "name": "Тоҷикӣ" },
  { "value": "so", "name": "Soomaali" },
  { "value": "uz", "name": "Oʻzbek tili" },
  { "value": "az", "name": "Azərbaycan dili" },
  { "value": "ro", "name": "Română" },
  { "value": "kk", "name": "Қазақ тілі" },
  { "value": "si", "name": "සිංහල" },
  { "value": "da", "name": "Dansk" },
  { "value": "sk", "name": "Slovenčina" },
  { "value": "fi", "name": "Suomi" },
  { "value": "no", "name": "Norsk" },
  { "value": "he", "name": "עברית" },
  { "value": "tt", "name": "Татар теле" },
  { "value": "hr", "name": "Hrvatski" },
  { "value": "bg", "name": "Български" },
  { "value": "sr", "name": "Српски" },
  { "value": "ca", "name": "Català" },
  { "value": "sl", "name": "Slovenščina" },
  { "value": "lt", "name": "Lietuvių kalba" },
  { "value": "lv", "name": "Latviešu valoda" },
  { "value": "et", "name": "Eesti keel" },
  { "value": "sq", "name": "Shqip" },
  { "value": "hy", "name": "Հայերեն" },
  { "value": "mn", "name": "Монгол хэл" },
  { "value": "ne", "name": "नेपाली" },
  { "value": "ps", "name": "پښتو" },
  { "value": "bo", "name": "བོད་སྐད་" },
  { "value": "eu", "name": "Euskara" },
  { "value": "cy", "name": "Cymraeg" },
  { "value": "br", "name": "Brezhoneg" },
  { "value": "lb", "name": "Lëtzebuergesch" },
  { "value": "is", "name": "Íslenska" },
  { "value": "fo", "name": "Føroyskt" },
  { "value": "yi", "name": "ייִדיש" },
  { "value": "gl", "name": "Galego" },
  { "value": "af", "name": "Afrikaans" },
  { "value": "am", "name": "አማርኛ" },
  { "value": "as", "name": "অসমীয়া" },
  { "value": "ba", "name": "Башҡорт теле" },
  { "value": "bs", "name": "Bosanski" },
  { "value": "ka", "name": "ქართული" },
  { "value": "kl", "name": "Kalaallisut" },
  { "value": "haw", "name": "ʻŌlelo Hawaiʻi" },
  { "value": "rw", "name": "Kinyarwanda" },
  { "value": "ku", "name": "Kurdî" },
  { "value": "lo", "name": "ພາສາລາວ" },
  { "value": "mg", "name": "Malagasy" },
  { "value": "mt", "name": "Malti" },
  { "value": "sd", "name": "سنڌي" },
  { "value": "ti", "name": "ትግርኛ" },
  { "value": "tk", "name": "Türkmen dili" },
  { "value": "zu", "name": "isiZulu" }
]